### ISSUE TITLE
Find a link

### ISSUE THREAD

**Issue by cgourdin** [erocci/erocci_backend_dbus#5]
Hello, 

After saving a link (thanks for your recent update), i want to get the link created details.
Erocci terminate Erocci-dbus-java with this : 

```
registered_name: testjava
    exception exit: {bad_return_value,
                        {undefined_attribute,<<"occi.core.target.kind">>}}
      in function  gen_server:terminate/7 (gen_server.erl, line `826)'''
```

With investigation, i found when Erocci call SaveLink method, it give to Erocci-Dbus-java attributes parameters the attribute "occi.core.target.kind" with value "undefined". 
if i remove this attribute on SaveLink call, it works with the Find(id) method.
For instance, i remove this attribute programmatically but should Erocci send me this attribute ?

**Comment by jeanparpaillon** [comment]
Fixed in  https://github.com/erocci/erocci_core/commit/65003974560547efa8a6487eba073f737877fbf7

Just to notice: a complete rewrite of OCCI Core model is in development and should be merged soon in erocci: https://github.com/erocci/erlang-occi

The first goal is to be able to use the OCCI Core model outside of erocci, but will also largely improve attributes management, schemas loading, mixins, etc
